"""followers

Revision ID: 09e4520a30c7
Revises: 636c2c12c5c6
Create Date: 2019-12-27 11:37:54.943879

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '09e4520a30c7'
down_revision = '636c2c12c5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
                    sa.Column('follower_id', sa.Integer(), nullable=True),
                    sa.Column('followed_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
